[package]
name = "imvoxloader"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
name = "imvoxloader"
crate-type = ["rlib"]

[dependencies]
imvoxcore = { path = "../core", version = "0.0.1" }
libloading = "0.9"
anyhow = "1"
